services:
  server:
    build:
      context: ..
      args:
        NEXT_PUBLIC_CIFARM_CORE_KEY: ${NEXT_PUBLIC_CIFARM_CORE_KEY}
        NEXT_PUBLIC_CIFARM_CORE_HOST: ${NEXT_PUBLIC_CIFARM_CORE_HOST}
        NEXT_PUBLIC_CIFARM_CORE_PORT: ${NEXT_PUBLIC_CIFARM_CORE_PORT}
        NEXT_PUBLIC_CIFARM_CORE_USE_SSL: ${NEXT_PUBLIC_CIFARM_CORE_USE_SSL}
        NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL}
        NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL}
        NEXT_PUBLIC_CIFARM_LOADER_URL: ${vars.NEXT_PUBLIC_CIFARM_LOADER_URL}
        NEXT_PUBLIC_CIFARM_DATA_URL: ${vars.NEXT_PUBLIC_CIFARM_DATA_URL}
        NEXT_PUBLIC_CIFARM_FRAMEWORK_URL: ${vars.NEXT_PUBLIC_CIFARM_FRAMEWORK_URL}
        NEXT_PUBLIC_CIFARM_WASM_URL: ${vars.NEXT_PUBLIC_CIFARM_WASM_URL}
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3053:3000
