services:
  server:
    build:
      context: ..
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_CIFARM_CORE_KEY: ${NEXT_PUBLIC_CIFARM_CORE_KEY}
      NEXT_PUBLIC_CIFARM_CORE_HOST: ${NEXT_PUBLIC_CIFARM_CORE_HOST}
      NEXT_PUBLIC_CIFARM_CORE_PORT: ${NEXT_PUBLIC_CIFARM_CORE_PORT}
      NEXT_PUBLIC_CIFARM_CORE_USE_SSL: ${NEXT_PUBLIC_CIFARM_CORE_USE_SSL}
      NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_API_URL}
      NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL: ${NEXT_PUBLIC_CIFARM_PERIPHERY_GRAPHQL_URL}
    ports:
      - 3053:3000
